name: Build and publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/s390x,linux/ppc64le,linux/arm64 -t  hiccupthebird/rmohr_activemq --push .
          docker manifest create hiccupthebird/rmohr_activemq hiccupthebird/rmohr_activemq:latest-amd64 hiccupthebird/rmohr_activemq:latest-s390x hiccupthebird/rmohr_activemq:latest-ppc64le hiccupthebird/rmohr_activemq:latest-arm64 
          docker manifest push hiccupthebird/rmohr_activemq
